Merge pull request #23038 from iyiguncevik/fix-azure-destroy
https://github.com/juju/juju/pull/23038

Cherry-picked commits of https://github.com/juju/juju/pull/23035

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

- Bootstrap with custom resrouce-group:

```
❯ juju bootstrap azure/eastus iyigun-test-ctrl \n --config resource-group-name=iyigun-test-group
[...]

❯ juju destroy-controller --destroy-all-models --no-prompt iyigun-test-ctrl --debug
[...]
14:24:10 DEBUG juju.provider.azure environ.go:206 discovered tenant id: 40a524d9-f848-46d4-a96f-be6df491fe15
14:24:10 WARN cmd destroy.go:264 This command will destroy the "iyigun-test-ctrl" controller and all its resources
14:24:10 INFO cmd destroy.go:295 Destroying controller
14:24:10 INFO cmd destroy.go:370 Waiting for model resources to be reclaimed
14:24:10 INFO cmd destroy.go:378 All models reclaimed, cleaning up controller machines
14:24:10 DEBUG juju.provider.azure environ.go:1921 destroying model "controller"
14:24:10 DEBUG juju.provider.azure environ.go:1931 deleting resources in user-specified resource group "iyigun-test-group"
14:24:10 DEBUG juju.provider.azure environ.go:2113 deleting all resources in iyigun-test-group
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-controller (Microsoft.Compute/availabilitySets)
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-2336a9-0 (Microsoft.Compute/disks)
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-2336a9-0 (Microsoft.Compute/virtualMachines)
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-2336a9-0-primary (Microsoft.Network/networkInterfaces)
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-internal-nsg (Microsoft.Network/networkSecurityGroups)
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-2336a9-0-public-ip (Microsoft.Network/publicIPAddresses)
14:24:16 DEBUG juju.provider.azure environ.go:2154 resource to delete: juju-internal-network (Microsoft.Network/virtualNetworks)
14:24:16 DEBUG juju.provider.azure environ.go:1245 canceling deployment for instance "juju-2336a9-0"
14:24:16 DEBUG juju.provider.azure environ.go:1318 - canceling deployment "juju-2336a9-0"
14:24:17 DEBUG juju.provider.azure environ.go:1291 deleting instance "juju-2336a9-0"
14:24:17 DEBUG juju.provider.azure environ.go:1365 - deleting virtual machine (juju-2336a9-0)
14:24:18 DEBUG juju.api monitor.go:35 RPC connection died
14:24:18 DEBUG juju.api monitor.go:35 RPC connection died
14:24:58 DEBUG juju.provider.azure environ.go:1376 - deleting OS disk (juju-2336a9-0)
14:24:59 DEBUG juju.provider.azure environ.go:1390 - deleting security rules (juju-2336a9-0)
14:24:59 DEBUG juju.provider.azure environ.go:1398 - deleting network interfaces (juju-2336a9-0)
14:25:01 DEBUG juju.provider.azure environ.go:1417 - deleting public IPs (juju-2336a9-0)
14:25:12 DEBUG juju.provider.azure environ.go:1437 - deleting deployment (juju-2336a9-0)
14:25:28 DEBUG juju.provider.azure environ.go:2248 deleting 3 resources
14:25:28 DEBUG juju.provider.azure environ.go:2264 - deleting resource "/subscriptions/fbcb21ca-f5c1-44d3-bbc0-37889b64b485/resourceGroups/iyigun-test-group/providers/Microsoft.Compute/availabilitySets/juju-controller"
14:25:28 DEBUG juju.provider.azure environ.go:2264 - deleting resource "/subscriptions/fbcb21ca-f5c1-44d3-bbc0-37889b64b485/resourceGroups/iyigun-test-group/providers/Microsoft.Network/networkSecurityGroups/juju-internal-nsg"
14:25:28 DEBUG juju.provider.azure environ.go:2264 - deleting resource "/subscriptions/fbcb21ca-f5c1-44d3-bbc0-37889b64b485/resourceGroups/iyigun-test-group/providers/Microsoft.Network/virtualNetworks/juju-internal-network"
14:25:39 DEBUG juju.provider.azure environ.go:2248 deleting 1 resources
14:25:39 DEBUG juju.provider.azure environ.go:2264 - deleting resource "/subscriptions/fbcb21ca-f5c1-44d3-bbc0-37889b64b485/resourceGroups/iyigun-test-group/providers/Microsoft.Network/networkSecurityGroups/juju-internal-nsg"
14:25:41 DEBUG juju.provider.azure environ.go:1936 deleting auto managed identities
14:25:42 DEBUG juju.provider.azure environ.go:1972 found role definition id:
14:25:42 DEBUG juju.provider.azure environ.go:1992 found role assignment id:
14:25:42 INFO cmd supercommand.go:578 command finished

❯ az resource list --resource-group iyigun-test-group --output table

```

- Bootstrap with default resrouce-group:

```
❯ juju bootstrap azure/eastus iyigun-test-ctrl
[...]

❯ az resource list --resource-group juju-controller-5f05a68f --output table
Name ResourceGroup Location Type Status
----------------------- ------------------------ ---------- --------------------------------------- ---------
juju-controller juju-controller-5f05a68f eastus Microsoft.Compute/availabilitySets Succeeded
juju-9e3b6b-0-public-ip juju-controller-5f05a68f eastus Microsoft.Network/publicIPAddresses Succeeded
juju-internal-nsg juju-controller-5f05a68f eastus Microsoft.Network/networkSecurityGroups Succeeded
juju-internal-network juju-controller-5f05a68f eastus Microsoft.Network/virtualNetworks Succeeded
juju-9e3b6b-0-primary juju-controller-5f05a68f eastus Microsoft.Network/networkInterfaces Succeeded
juju-9e3b6b-0 juju-controller-5f05a68f eastus Microsoft.Compute/virtualMachines Succeeded
juju-9e3b6b-0 JUJU-CONTROLLER-5F05A68F eastus Microsoft.Compute/disks Succeeded

❯ juju destroy-controller --destroy-all-models --no-prompt iyigun-test-ctrl --debug
[...]
14:46:07 DEBUG juju.provider.azure environ.go:206 discovered tenant id: 40a524d9-f848-46d4-a96f-be6df491fe15
14:46:08 DEBUG juju.provider.azure environ.go:2337 legacy resource group name doesn't exist, using short name
14:46:08 WARN cmd destroy.go:264 This command will destroy the "iyigun-test-ctrl" controller and all its resources
14:46:08 INFO cmd destroy.go:295 Destroying controller
14:46:09 INFO cmd destroy.go:370 Waiting for model resources to be reclaimed
14:46:09 INFO cmd destroy.go:378 All models reclaimed, cleaning up controller machines
14:46:09 DEBUG juju.provider.azure environ.go:1921 destroying model "controller"
14:46:09 DEBUG juju.provider.azure environ.go:1923 deleting resource groups
14:46:11 DEBUG juju.provider.azure environ.go:2057 - deleting resource group "juju-controller-5f05a68f"
14:46:18 DEBUG juju.api monitor.go:35 RPC connection died
14:46:18 DEBUG juju.api monitor.go:35 RPC connection died
14:50:24 DEBUG juju.provider.azure environ.go:1936 deleting auto managed identities
14:50:25 DEBUG juju.provider.azure environ.go:1972 found role definition id:
14:50:26 DEBUG juju.provider.azure environ.go:1992 found role assignment id:
14:50:27 DEBUG juju.rpc server.go:356 error closing codec: write tcp 192.168.1.28:58090->13.92.69.15:17070: write: connection timed out
write tcp 192.168.1.28:58090->13.92.69.15:17070: write: broken pipe
14:50:27 DEBUG juju.rpc server.go:356 error closing codec: write tcp 192.168.1.28:58086->13.92.69.15:17070: write: connection timed out
write tcp 192.168.1.28:58086->13.92.69.15:17070: write: broken pipe
14:50:27 INFO cmd supercommand.go:578 command finished

❯ az resource list --resource-group juju-controller-5f05a68f --output table
(ResourceGroupNotFound) Resource group 'juju-controller-5f05a68f' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'juju-controller-5f05a68f' could not be found.
```