add-juju-bridge.py: python3.5 fixes
In python 3.5 we get:

Traceback (most recent call last):
  File "./add-juju-bridge.py", line 372, in <module>
    main(arg_parser().parse_args())
  File "./add-juju-bridge.py", line 351, in main
    print_shell_cmd("echo cat {}".format(args.filename))
  File "./add-juju-bridge.py", line 279, in print_shell_cmd
    print(out.rstrip('\n'))

  TypeError: a bytes-like object is required, not 'str'

We fix this by first decoding the stream before calling rstrip().