Revert to crypto version that compiles on armhf
Fixes lp:1547741 by switching to a golang.org/x/crypto
version that predates inclusion of arm assembly code.

This avoids the compilation error on go 1.2:

  poly1305/poly1305_arm.s:26 syntax error, last name: R9

Juju itself builds fine with this crypto version, other branches
may have dependencies on code only found in more recent copies.