Avoid use of ##[add-path] in GitHub Actions
This is already done in the develop branch. Whitespace changes are to
match the version of this file in develop too.

This causes the following failure due to a GitHub Actions change:

https://github.com/juju/juju/pull/12324/checks?check_run_id=1408765804:

Error: Unable to process command '+ echo '##[add-path]/snap/bin'' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '##[add-path]/snap/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/